services:
  db:
    container_name: ${NAME}_postgres
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - lan

  api:
    container_name: ${NAME}_api
    build: ./api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - lan
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}_api.entrypoints=websecure"
      - "traefik.http.routers.${NAME}_api.rule=Host(`${NAME}.jrcan.dev`) && PathPrefix(`/api`)"
      - "traefik.http.routers.${NAME}_api.tls=true"
      - "traefik.http.routers.${NAME}_api.tls.certresolver=myresolver"

  web:
    container_name: ${NAME}_web
    build: ./web
    restart: unless-stopped
    volumes:
      - ./web/src:/var/www/html
    depends_on:
      - api
    networks:
      - lan
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}_web.entrypoints=websecure"
      - "traefik.http.routers.${NAME}_web.rule=Host(`${NAME}.jrcan.dev`)"
      - "traefik.http.routers.${NAME}_web.tls=true"
      - "traefik.http.routers.${NAME}_web.tls.certresolver=myresolver"

volumes:
  postgres_data:

networks:
  web:
    external: true
  lan:
    external: false
    name: lan_${NAME}
